version: '3.8'

services:
  app:
    # container_name: petclinic-app
    image: "3laaharrrr/petclinic:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic
    deploy:
      replicas: 5
    # ports:
    #   - "8080:8080"
    depends_on:
      - mysql

  nginx:
    container_name: petclinic-nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app    

  mysql:
    container_name: petclinic-mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - petclinicvolume:/var/lib/mysql

volumes:
  petclinicvolume:
