version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090
    restart: unless-stopped
    networks:
      - monitoring


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"  # Ensure this line is present
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
