global:
  scrape_interval: 15s # Set the interval for scraping metrics

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Scrape Prometheus itself

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"] # Scrape Node Exporter running on the same server
